# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iRonhead
email: ironhead.chuang at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.ironhead.ninja/projects/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  imironhead

# Build settings
markdown: kramdown

collections:
  paints:
    output: true
    permalink: /paints/:path/
  aigossips:
    output: true
    permalink: /aigossips/:path/
